// NOTE This file is auto-generated by the Contentlayer CLI

import research__whatIsTheTutorialHellAndHowToEscapeItCopy_2Mdx from './Post/research__what-is-the-tutorial-hell-and-how-to-escape-it copy 2.mdx.json'

export const allPosts = [research__whatIsTheTutorialHellAndHowToEscapeItCopy_2Mdx]
