// NOTE This file is auto-generated by the Contentlayer CLI

import { Post, Project, Snippet, DocumentTypes } from './types'

export type * from './types'

export declare const allPosts: Post[]
export declare const allProjects: Project[]
export declare const allSnippets: Snippet[]

export declare const allDocuments: DocumentTypes[]

