// NOTE This file is auto-generated by the Contentlayer CLI

export { isType } from 'contentlayer/client'

export * from './allPosts.mjs'
export * from './allProjects.mjs'
export * from './allSnippets.mjs'

import { allPosts } from './allPosts.mjs'
import { allProjects } from './allProjects.mjs'
import { allSnippets } from './allSnippets.mjs'

export const allDocuments = [...allPosts, ...allProjects, ...allSnippets]
